name: Run Tests on Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # your project's version

    - name: Restore backend
      run: dotnet restore HeadcountAllocation/HeadcountAllocation.csproj

    - name: Restore tests
      run: dotnet restore Tests.Tests/Tests.Tests.csproj

    - name: Build backend
      run: dotnet build HeadcountAllocation/HeadcountAllocation.csproj --no-restore

    - name: Build tests
      run: dotnet build Tests.Tests/Tests.Tests.csproj --no-restore

    - name: Run tests
      run: dotnet test Tests.Tests/Tests.Tests.csproj --no-build --verbosity normal
